name: 'Auto assign PR and request review'
description: 'Auto assign PR and request review'
author: '@nostradini'
branding:
  icon: 'bar-chart'
  color: 'yellow'
inputs:
  token:
    description: 'GitHub token'
    default: ${{ github.token }}
    required: false
  reviewers:
    description: 'GitHub usernames'
    required: false
    default: 'ekojyppah , nostradini'
  team-reviewers:
    description: 'GitHub teams'
    required: false
runs:
  using: 'node12'
  main: 'index.js'