name: Reviewer

on:
#   push:
#     branches: [ "main" ]
  pull_request:
    # branches: [ "main" ]
    types: 
      - opened

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  add-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
