name: API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  API:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Running Logic
        run: |
           curl -i -u nostradini@${{secret.TEST_TOKEN}} https://api.github.com/git_beginner
