name: API
on:
  push:
    branches: [ main ]
  #pull_request:
    #branches: [ main ]

  workflow_dispatch:
env:
  PAT: ${{secrets.TEST_TOKEN}}
jobs:
  API:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Running Logic
        run: |
          echo '${curl -X GET https://api.github.com/repos/nostradini/MYREPO2/contents/VERSION | jq .sha } '
