name: Check on Protection

on:
  push:
    branches: [ main ]

jobs:
  Check-protection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup GIT
        run: |
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"

      - name: Branch protection OFF
        uses: octokit/request-action@v2.x
        with:
         route: PUT /repos/:repository/branches/master/protection
         repository: ${{ github.repository }}
         required_status_checks: |
          null
         enforce_admins: |
          null
         required_pull_request_reviews: |
          null
         restrictions: | 
          null 
        env:
         GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_REPO_ADMIN_CI_TOKEN }}
       
       
