name: "Changelog"

on: # yamllint disable-line rule:truthy
  # push:
  #   tags:
  #     - "**"
  push:
    branches: [main]
    paths-ignore:
     - 'CHANGELOG.md'

jobs:
  Change_Log:
    runs-on: "ubuntu-latest"
    steps:
    - name: "Create local changelog"
      run: |
        chmod +x ./script/changeLOG.sh
        ./script/changeLOG.sh