name: Protected_Branch_auto

on:
    pull_request:
        branches: [ main ]
env:
  lastCommit: ${{ github.event.commits[0].message }}
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: hmarr/auto-approve-action@v2
      if: github.actor == 'dependabot[bot]'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Show something
      run: |
       echo ${{ env.lastCOmmit }}
    
