name: Commit ID

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Logic Script
        run: echo Hello, world!
      - name: Dump GitHub context
        env:
         GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
     #   run: |
     #     echo Add other actions to build,
    #      echo test, and deploy your project.
