name: Get Reviewer

on:
  # push:
  #   branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened,ready_for_review,reopened]

jobs:
  add-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run review
        uses: ./actions2
        with:
           reviewers: ekojyppah

