name: Versioning

on:
  # push:
  #   branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
env:
  lastCommit: ${{ github.event.commits[0].message }}
jobs:
  add-review:
    runs-on: ubuntu-latest
    steps:
      - name: Run review
        uses: ./

