name: Template Workflow
on:
  push:
    branches: [main]

env:
  message: ${{ github.event.head_commit.message }}
  ENV_TOKEN: ${{ secrets.DOOR }}
jobs:
  run_script:
    runs-on: ubuntu-latest
    outputs:
      COUNTER: Commit count
      LASTCOM: Last commit
      envgitmojiko: Chnage type
      envMajor: colMajor
      envMinor: colMinor
      envPatch: colPatch
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: RUN COUNTER
      id: value
      run: |
        chmod +x ./script/initialize_checkpoints.sh
        ./script/initialize_checkpoints.sh

    - name: Apply Logic
      id: logic
      run: |
        chmod +x ./script/do_logic.sh
        ./script/do_logic.sh

    - name: TEST VALUE
      run: |
        echo "commit count= ${{ steps.value.outputs.COUNTER }}"
        echo "last commit= ${{ steps.value.outputs.LASTCOM }}"
        echo "envgitmojiko= ${{ steps.logic.outputs.envgitmojiko }}"
        echo "envMajor= ${{ steps.logic.outputs.envMajor }}"
        echo "envMinor= ${{ steps.logic.outputs.envMinor }}"
        echo "envPatch= ${{ steps.logic.outputs.envPatch }}"

    - name: Work on logic
      id: setvar
      run: |
        
        # echo "ver_major=$ver_major,ver_minor=$ver_minor,ver_patch=$ver_patch"
        # echo "data= " $data
        
    - name: Release Notes
      run: |


        # chmod +x ./script/releaseNOTES.sh
        # ./script/releaseNOTES.sh


    # - name: Dump GitHub context
    #   env:
    #       GITHUB_CONTEXT: ${{ toJson(github) }}
      # run: echo "$GITHUB_CONTEXT"
      
    - name: Delete tags
      run: |
        echo "message= " $message
        # git config --global user.email "github-actions[bot]@users.noreply.github.com"
        # git config --global user.name "github-actions[bot]"
        # git tag -l | xargs -n 1 git push --delete origin
        # git tag | xargs git tag -d
