name: Template Workflow
on:
  push:
    branches: [main]
env:
  message: ${{ github.event.head_commit.message }}
  ENV_TOKEN: ${{ secrets.DOOR }}
jobs:
  run_script:
    runs-on: ubuntu-latest
    outputs:
      ENV_COUNT: ${{ steps.setvar.outputs.arrcount }}
      # ENV_VER: ${{ steps.setvar.outputs.sh_ver }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Delete tags
      run: |
        echo "message= " $message
        # git config --global user.email "github-actions[bot]@users.noreply.github.com"
        # git config --global user.name "github-actions[bot]"
        # git tag -l | xargs -n 1 git push --delete origin
        # git tag | xargs git tag -d
    - name: work on logic
      id: setvar
      run: |
        chmod +x ./script/get_defaults.sh
        ./script/get_defaults.sh
        echo "CN=" $cn
        echo "COUNT=$ENV_COUNT" >> $GITHUB_ENV
  
    - name: Release Notes
      run: |
         echo "count =" $COUNT
         echo "value form env= " ${{needs.run_script.outputs.ENV_COUNT}}
        # chmod +x ./script/releaseNOTES.sh
        # ./script/releaseNOTES.sh


    # - name: Dump GitHub context
    #   env:
    #       GITHUB_CONTEXT: ${{ toJson(github) }}
      # run: echo "$GITHUB_CONTEXT"
      