name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
env:
  lastCommit: ${{ github.event.commits[0].message }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          temp=$(cat "VERSION")
          var1="${temp:8:1}"
          var2="${temp:10:1}"
          var3="${temp:12:1}"
          echo "${{ env.lastCommit }}"
          varA="${{ env.lastCommit }}"
          lowerstr=$(echo $varA |tr '[:upper:]' '[:lower:]')
          echo "lower = $lowerstr"
          if [[ "$lowerstr" == *"#major"* ]]
          then
          echo "Found major in commit"
          var1=$((var1+1))
          var2=0
          var3=0
          elif [[ "$lowerstr" == *"#minor"* ]]
          then
          echo "Found minor in commit"
          var2=$((var2+1))
          var3=0
          elif [[ "$lowerstr" == *"#patch"* ]]
          then
          echo "Found patch in commit"
          var3=$((var3+1))
          else
          echo "Default condition"
          var3=$((var3+1))
          fi
          
          echo "var1 $var1 , var2 $var2 , var3 $var3"
         
          cat /dev/null > VERSION
          echo -n "Version $var1.$var2.$var3 - ${{ env.lastCommit }}" > VERSION
      - name: Push changes
        env:
            credentials1: ${{ secrets.EMAIL_CREDENTIALS }}
            credentials2: ${{ secrets.NAME_CREDENTIALS }}
        run: |
          git config --global user.email "${{ env.credentials1 }}"
          git config --global user.name "${{ env.credentials2 }}"
          git add VERSION
          git commit -m "updated file for versioning"
          git fetch origin main
          git push origin HEAD:main --force
