name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
env:
  lastCommit: ${{ github.event.commits[0].message }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          dir
          chmod +x ./git_beginner/action_script/version_update.sh
          ./git_beginner/action_script/version_update.sh
        shell: bash
          
      - name: Push changes
        env:
            credentials1: ${{ secrets.EMAIL_CREDENTIALS }}
            credentials2: ${{ secrets.NAME_CREDENTIALS }}
        run: |
          git config --global user.email "${{ secrets.EMAIL_CREDENTIALS }}"
          git config --global user.name "${{ secrets.NAME_CREDENTIALS }}"
          git add VERSION
          git commit -m "updated file for versioning"
          git fetch origin main
          git push origin HEAD:main
